FROM openjdk:17-jdk-alpine

RUN apk add --no-cache netcat-openbsd

WORKDIR /app

COPY . /app/

COPY wait-for-eureka.sh /wait-for-eureka.sh
RUN chmod +x /wait-for-eureka.sh

EXPOSE 8080

CMD ["/wait-for-eureka.sh"]